### ISSUE TITLE
Add the possibility to modify max_tokens

### ISSUE THREAD

**Issue by billmetangmo** [approximatelabs/lambdaprompt#6]
Hi

First off, I'd like to say that I'm a big fan of the lambdaprompt project and I really appreciate the hard work you've put into it.

I was wondering if it would be possible to add a customizable max_tokens parameter to the project. Currently, this parameter is hard-coded to 500 and I think it would be really useful to have the option to adjust it based on individual needs. For example, I needed to ask gpt to do bulk clean postal adress but slice it to multiple parts because of the 500 limitaion knowing that the maximum is 4k

Best regards,

**Comment by bluecoconut** [comment]
Thanks for the ask

Quickly added this now. Should be available: `pip install -U lambdaprompt` to make sure you're on 0.4.2 and it should be available.
