### ISSUE TITLE
Will there be a Typescript/Javascript version?

### ISSUE THREAD

**Issue by MRYingLEE** [approximatelabs/lambdaprompt#8]
I am using Node.js to code some ChatGPT-related functions.

Just wonder whether there will be a Typescript/Javascript version.

If ChatGPT can convert this repo from Python to Typescript, it will be amazing. So far in GPT-3.5, the token limit stops my converting. I have no access to GPT4-8k or GPT-32k.

**Comment by bluecoconut** [comment]
Hey, I like the idea but probably not. If you do create one and put it up let me know though!

I'm not that good at all the async gotchas in javascript so it'd be a pretty big endeavor for me to make it as lightweight but capture the same essence. Additionally, A lot of the logic in this is based around python decorator concept as well as the hiccups of asyncio in python, which don't really translate. Also, I'm not sure if in javascript ecosystem if `jinja` templates are well known, there might be better templating solutions that are more natural. 

All in all, I like the idea, and would likely use it if it did exist in javascript, so keep me in the loop if you do end up making it!
